### ISSUE TITLE
A more explained step-by-step please

### ISSUE THREAD

**Issue by Nazarennno** [rxfe-a/vision-web#4]
I'm doing this on Roblox Studio and I think I get the steps wrong.

**Comment by graxe20** [comment]
Maybe, read the instructions.

**Comment by rxfe-a** [comment]
> I'm doing this on Roblox Studio and I think I get the steps wrong.

add on discord rxfe.a

**Comment by rxfe-a** [comment]
fortunately this isnt a real issue so I will have to close the Repo
